In [143]:
import pandas as pd

df = pd.read_csv("club_signups.csv")
df.head()

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Soccer,2026-09-15 13:39,N
1,S010,61-3846,AHMED ZAKI,ahmed.zaki@student.guc.edu.eg,Management,alexandria,Chess,15/09/2026 03:12,false
2,S008,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Music,2026-09-14 23:32,Y
3,S035,61-4844,MOHAMED ADEL,mohamed.adel@student.guc.edu.eg,Engineering and Materials Science,Cairo,Debating,2026-09-17 11:15,yes
4,S004,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Chess Club,2026-09-13 22:36,yes

In [144]:
print(df.shape)
print(df.dtypes)

for col in ["faculty", "club", "city", "fee_paid"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

(39, 9)
signup_id       object
student_id      object
full_name       object
email           object
faculty         object
city            object
club            object
signed_up_at    object
fee_paid        object
dtype: object

--- faculty ---
faculty
Pharmacy                                  7
EMS                                       7
IET                                       5
Management                                4
Information Engineering and Technology    4
MET                                       3
iet                                       3
Engineering and Materials Science         1
Pharma                                    1
met                                       1
Media Engineering and Technology          1
pharmacy                                  1
ems                                       1
Name: count, dtype: int64

--- club ---
club
Robotics       8
Music          5
Chess          4
football       4
Debating       3
Chess Club     3
Football       3
Soccer         2
music          2
chess          2
debate club    1
Music          1
Debate         1
Name: count, dtype: int64

--- city ---
city
Cairo         13
Alexandria    11
Giza           4
Alex           4
cairo          2
giza           2
alexandria     1
CAIRO          1
El Giza        1
Name: count, dtype: int64

--- fee_paid ---
fee_paid
yes      7
1        7
false    6
Y        5
N        4
TRUE     4
Yes      4
0        1
no       1
Name: count, dtype: int64

In [145]:
for col in ["faculty", "club", "city"]:
    df[col] = df[col].str.strip().str.lower()

for col in ["faculty", "club", "city"]:
    print(df[col].value_counts(), "\n")

faculty
pharmacy                                  8
ems                                       8
iet                                       8
management                                4
met                                       4
information engineering and technology    4
engineering and materials science         1
pharma                                    1
media engineering and technology          1
Name: count, dtype: int64

club
music          8
robotics       8
football       7
chess          6
debating       3
chess club     3
soccer         2
debate club    1
debate         1
Name: count, dtype: int64

city
cairo         16
alexandria    12
giza           6
alex           4
el giza        1
Name: count, dtype: int64

In [146]:
faculty_map = {
    "met": "MET",
    "media engineering and technology": "MET",
    "iet": "IET",
    "information engineering and technology": "IET",
    "ems": "EMS",
    "engineering and materials science": "EMS",
    "pharmacy": "Pharmacy",
    "pharma": "Pharmacy",
    "management": "Management",
}

club_map = {
    "robotics": "Robotics",
    "debate": "Debate",
    "debating": "Debate",
    "debate club": "Debate",
    "music": "Music",
    "football": "Football",
    "soccer": "Football",
    "chess": "Chess",
    "chess club": "Chess",
}

city_map = {
    "cairo": "Cairo",
    "giza": "Giza",
    "el giza": "Giza",
    "alexandria": "Alexandria",
    "alex": "Alexandria",
}

df["faculty"] = df["faculty"].map(faculty_map)
df["club"] = df["club"].map(club_map)
df["city"] = df["city"].map(city_map)

In [147]:
assert set(df["faculty"]) <= {"MET", "IET", "EMS", "Pharmacy", "Management"}
assert set(df["club"]) <= {"Robotics", "Debate", "Music", "Football", "Chess"}
assert set(df["city"]) <= {"Cairo", "Giza", "Alexandria"}

In [148]:
for col in ["faculty", "club", "city"]:
    print(df[col].value_counts(dropna=False), "\n")

faculty
IET           12
Pharmacy       9
EMS            9
MET            5
Management     4
Name: count, dtype: int64

club
Football    9
Chess       9
Music       8
Robotics    8
Debate      5
Name: count, dtype: int64

city
Alexandria    16
Cairo         16
Giza           7
Name: count, dtype: int64

In [149]:
df["fee_paid"].value_counts()

fee_paid
yes      7
1        7
false    6
Y        5
N        4
TRUE     4
Yes      4
0        1
no       1
Name: count, dtype: int64

In [150]:
fee_map = {
    "y": True, "yes": True, "true": True, "1": True,
    "n": False, "no": False, "false": False, "0": False,
}

df["fee_paid"] = df["fee_paid"].astype(str).str.strip().str.lower().map(fee_map)

assert df["fee_paid"].isna().sum() == 0
df["fee_paid"] = df["fee_paid"].astype(bool)
assert df["fee_paid"].dtype == bool

df["fee_paid"].value_counts()

fee_paid
True     27
False    12
Name: count, dtype: int64

In [151]:
df["signed_up_at"].head(10)

0    2026-09-15 13:39
1    15/09/2026 03:12
2    2026-09-14 23:32
3    2026-09-17 11:15
4    2026-09-13 22:36
5    15/09/2026 03:42
6    2026-09-14 17:03
7    2026-09-13 23:52
8    2026-09-15 23:07
9    2026-09-16 09:07
Name: signed_up_at, dtype: object

In [152]:
s = df["signed_up_at"].str.strip()

iso = pd.to_datetime(s, format="%Y-%m-%d %H:%M", errors="coerce")
dmy = pd.to_datetime(s, format="%d/%m/%Y %H:%M", errors="coerce")

print("ISO rows:", iso.notna().sum())
print("day/month rows:", dmy.notna().sum())

df["signed_up_at"] = iso.fillna(dmy)

assert df["signed_up_at"].isna().sum() == 0
print(df["signed_up_at"].dtype)
print(df["signed_up_at"].min(), "to", df["signed_up_at"].max())

ISO rows: 25
day/month rows: 14
datetime64[ns]
2026-09-13 14:36:00 to 2026-09-18 23:36:00

In [153]:
df.to_csv("club_signups_clean.csv", index=False)

In [154]:
check = pd.read_csv("club_signups_clean.csv")
print(check.shape)
check.head()

(39, 9)

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Football,2026-09-15 13:39:00,False
1,S010,61-3846,AHMED ZAKI,ahmed.zaki@student.guc.edu.eg,Management,Alexandria,Chess,2026-09-15 03:12:00,False
2,S008,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Music,2026-09-14 23:32:00,True
3,S035,61-4844,MOHAMED ADEL,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Debate,2026-09-17 11:15:00,True
4,S004,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Chess,2026-09-13 22:36:00,True

In [155]:
print("Rows before:", len(df))
n_exact = df.duplicated().sum()
print("Exact duplicates:", n_exact)
print(df[df.duplicated(keep=False)].sort_values("signup_id"))

df = df.drop_duplicates()
print("Rows after:", len(df))

Rows before: 39
Exact duplicates: 3
   signup_id student_id   full_name                          email   faculty  \
0       S015    61-8942   Hana Zaki   hana.zaki@student.guc.edu.eg  Pharmacy
34      S015    61-8942   Hana Zaki   hana.zaki@student.guc.edu.eg  Pharmacy
15      S022    61-8224   Sara Zaki   sara.zaki@student.guc.edu.eg       EMS
24      S022    61-8224   Sara Zaki   sara.zaki@student.guc.edu.eg       EMS
20      S023    58-1125  Ziad Saleh  ziad.saleh@student.guc.edu.eg       IET
33      S023    58-1125  Ziad Saleh  ziad.saleh@student.guc.edu.eg       IET

     city      club        signed_up_at  fee_paid
0    Giza  Football 2026-09-15 13:39:00     False
34   Giza  Football 2026-09-15 13:39:00     False
15   Giza     Music 2026-09-16 01:39:00      True
24   Giza     Music 2026-09-16 01:39:00      True
20  Cairo     Chess 2026-09-16 09:29:00     False
33  Cairo     Chess 2026-09-16 09:29:00     False
Rows after: 36

In [156]:
df.to_csv("club_signups_clean.csv", index=False)

In [157]:
dups = df[df.duplicated(subset=["student_id", "club"], keep=False)]
dups.sort_values(["student_id", "club", "signed_up_at"])[
    ["signup_id", "student_id", "full_name", "club", "signed_up_at", "fee_paid"]
]

,signup_id,student_id,full_name,club,signed_up_at,fee_paid
8,S020,55-9245,ali ibrahim,Music,2026-09-15 23:07:00,False
9,S033,55-9245,ali ibrahim,Music,2026-09-16 09:07:00,True
22,S021,61-4844,Mohamed Adel,Debate,2026-09-16 01:15:00,False
3,S035,61-4844,MOHAMED ADEL,Debate,2026-09-17 11:15:00,True
35,S017,61-7344,Laila Mostafa,Debate,2026-09-15 18:01:00,False
25,S034,61-7344,Laila Mostafa,Debate,2026-09-16 02:01:00,True
21,S032,61-7344,Laila Mostafa,Football,2026-09-17 23:36:00,False
38,S036,61-7344,Laila Mostafa,Football,2026-09-18 23:36:00,True

In [158]:
before = len(df)
df = (
    df.sort_values("signed_up_at")
      .drop_duplicates(subset=["student_id", "club"], keep="last")
)
print("Removed:", before - len(df))
print("Rows left:", len(df))

Removed: 4
Rows left: 32

In [159]:
assert not df.duplicated(subset=["student_id", "club"]).any()

df.to_csv("club_signups_clean.csv", index=False)

check = pd.read_csv("club_signups_clean.csv")
print(check.shape)
check.head()

(32, 9)

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S001,58-9118,Mariam Kamel,mariam.kamel@student.guc.edu.eg,IET,Giza,Robotics,2026-09-13 14:36:00,True
1,S002,55-2992,mohamed adel,mohamed.adel@student.guc.edu.eg,IET,Alexandria,Debate,2026-09-13 15:38:00,True
2,S003,55-9245,Ali Ibrahim,ali.ibrahim@student.guc.edu.eg,MET,Cairo,Chess,2026-09-13 21:16:00,True
3,S004,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Chess,2026-09-13 22:36:00,True
4,S005,61-4733,OMAR ADEL,omar.adel@student.guc.edu.eg,EMS,Cairo,Football,2026-09-13 23:52:00,True

In [160]:
raw = pd.read_csv("club_signups.csv").drop_duplicates()
n_raw = raw.duplicated(subset=["student_id", "club"]).sum()
print("Resubmissions found BEFORE fixing club names:", n_raw)

Resubmissions found BEFORE fixing club names: 2